/**
 * Copyright 2026-present Termlnk
 *
 * Licensed under the PolyForm Noncommercial License 1.0.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://polyformproject.org/licenses/noncommercial/1.0.0
 *
 * Use of this software for any commercial purpose is prohibited.
 * The software is provided "AS IS", WITHOUT WARRANTY OR CONDITION OF ANY KIND,
 * either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

/**
 * Auth wire format — mirror of the desktop client's @termlnk/auth-core HTTP services.
 *
 * Sources of truth (do not drift):
 *   - termlnk/packages/auth-core/src/services/http-auth.service.ts (register / srp/init / srp/verify / logout)
 *   - termlnk/packages/auth-core/src/services/http-token-refresher.service.ts (refresh)
 */

import { z } from 'zod';

const emailSchema = z.string().email().min(3).max(255);
const base64Schema = z.string().regex(/^[A-Za-z0-9+/=]+$/, 'must be base64');
const hexSchema = z.string().regex(/^[0-9a-fA-F]+$/, 'must be hex');
const displayNameSchema = z.string().min(1).max(120);

export const userAccountSchema = z.object({
  id: z.string().min(1),
  email: emailSchema,
  displayName: z.string().optional(),
  avatarUrl: z.string().optional(),
  emailVerified: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});
export type IUserAccount = z.infer<typeof userAccountSchema>;

export const tokenPairSchema = z.object({
  accessToken: z.string().min(1),
  refreshToken: z.string().min(1),
  /** ms epoch */
  accessTokenExpiresAt: z.number().int().nonnegative(),
  /** ms epoch */
  refreshTokenExpiresAt: z.number().int().nonnegative(),
});
export type ITokenPair = z.infer<typeof tokenPairSchema>;

/* ───── POST /auth/register ───── */

export const registerRequestSchema = z.object({
  email: emailSchema,
  /** base64 of the 32-byte random salt portion (full salt = utf8(lowercased(email)) || decode(this)) */
  argon2SaltB64: base64Schema,
  /** SRP6a salt (hex) — generated by client */
  srpSalt: hexSchema,
  /** SRP6a verifier (hex) — derived from authKeyHex by client */
  srpVerifier: hexSchema,
  displayName: displayNameSchema.optional(),
  /** Optional human-readable device label (e.g. `os.hostname()`); shown in the device list */
  deviceName: z.string().min(1).max(120).optional(),
});
export type IRegisterRequest = z.infer<typeof registerRequestSchema>;

export const registerResponseSchema = z
  .object({
    user: userAccountSchema,
  })
  .merge(tokenPairSchema);
export type IRegisterResponse = z.infer<typeof registerResponseSchema>;

/* ───── POST /auth/srp/init ───── */

export const srpInitRequestSchema = z.object({
  email: emailSchema,
});
export type ISrpInitRequest = z.infer<typeof srpInitRequestSchema>;

export const srpInitResponseSchema = z.object({
  argon2SaltB64: base64Schema,
  srpSalt: hexSchema,
  /** B (server public ephemeral, hex) */
  srpServerEphemeralPublic: hexSchema,
});
export type ISrpInitResponse = z.infer<typeof srpInitResponseSchema>;

/* ───── POST /auth/srp/verify ───── */

export const srpVerifyRequestSchema = z.object({
  email: emailSchema,
  /** A (client public ephemeral, hex) */
  clientPublicEphemeral: hexSchema,
  /** M1 (client session proof, hex) */
  clientSessionProof: hexSchema,
  /** Optional device label; same role as in registerRequest */
  deviceName: z.string().min(1).max(120).optional(),
});
export type ISrpVerifyRequest = z.infer<typeof srpVerifyRequestSchema>;

export const srpVerifyResponseSchema = z
  .object({
    /** M2 (server session proof, hex) */
    serverSessionProof: hexSchema,
    user: userAccountSchema,
  })
  .merge(tokenPairSchema);
export type ISrpVerifyResponse = z.infer<typeof srpVerifyResponseSchema>;

/* ───── GET /auth/me ───── */
/* Bearer auth. Server looks up the authenticated user record and returns it.
 * Used by the desktop client at startup to self-heal stale cached user fields
 * (displayName, avatarUrl, emailVerified). */

export const meResponseSchema = z.object({
  user: userAccountSchema,
});
export type IMeResponse = z.infer<typeof meResponseSchema>;

/* ───── POST /auth/refresh ───── */

export const refreshRequestSchema = z.object({
  refreshToken: z.string().min(1),
});
export type IRefreshRequest = z.infer<typeof refreshRequestSchema>;

export const refreshResponseSchema = tokenPairSchema;
export type IRefreshResponse = z.infer<typeof refreshResponseSchema>;

/* ───── POST /auth/logout ───── */
/* Bearer auth, empty body, 204 response. */

/* ───── GET /auth/devices ───── */
/* Returned shape lists every active (non-revoked, non-expired) refresh token for the user.
 * `id` is the refresh-token jti (opaque to humans, stable across the device's lifetime).
 * `isCurrent` is true for the device making the request — handy for the UI to show "this device". */

export const deviceSchema = z.object({
  id: z.string().uuid(),
  /** human label or null if the client didn't supply one */
  deviceName: z.string().nullable(),
  /** raw User-Agent header captured at issue time */
  userAgent: z.string().nullable(),
  /** ISO timestamp */
  createdAt: z.string(),
  /** ISO timestamp of the last refresh-token rotation */
  lastSeenAt: z.string(),
  /** ISO timestamp; refresh token expiry */
  expiresAt: z.string(),
  isCurrent: z.boolean(),
});
export type IDevice = z.infer<typeof deviceSchema>;

export const deviceListResponseSchema = z.object({
  devices: z.array(deviceSchema),
});
export type IDeviceListResponse = z.infer<typeof deviceListResponseSchema>;

/* ───── POST /auth/devices/:id/revoke ───── */
/* Empty body; the path parameter (refresh-token jti) identifies the device.
 * Revoking the *current* device is allowed — it is the equivalent of "log this device out
 * remotely". The server returns 204 either way; it never reveals whether the id existed. */

/* ───── error envelope ─────
 * Single shape for ALL non-2xx responses (including 4xx validation errors and 5xx).
 * `code` is the stable machine-readable identifier; clients should branch on it.
 * `message` is human-readable, optional — omitted when the code alone is self-describing
 * or when the server intentionally withholds internal detail (e.g. 5xx).
 * `details` carries field-level errors for `invalid_request` (zod validation failures);
 * each entry has the dotted-path-style `path` and a per-field `message`.
 */

export const errorDetailSchema = z.object({
  path: z.array(z.union([z.string(), z.number()])),
  message: z.string(),
});
export type IErrorDetail = z.infer<typeof errorDetailSchema>;

export const errorResponseSchema = z.object({
  error: z.object({
    code: z.string(),
    message: z.string().optional(),
    details: z.array(errorDetailSchema).optional(),
  }),
});
export type IErrorResponse = z.infer<typeof errorResponseSchema>;
